### DISCUSSION TITLE
Backup & Restore

### DISCUSSION THREAD

**Discussion by porscheme** [vesoft-inc/nebula#4467] [Q&A]
@wey-gu , following is one of the limitations of Backup & Restore 

- The backup graph space can be restored to the original cluster only. Cross clusters restoration is not supported.
 -- What does this really mean? 
 --Let's say my cluster A (3 metad, 3 graphd, 5 storaged), do the back
 --Can I restore to cluster B (3 metad, 3 graphd, 5 storaged) in different region?

**Comment by wey-gu** [comment]
@kqzh From my understanding, now BR is not designed for one cluster only, is it possible to make it work between clusters with exactly the same number of metad and storage(as above)?

Thanks!

**Reply by porscheme** [reply]
Thanks @wey-gu for the reply.

- There is no way to attach a NFS volume to Nebula cluster for backup & restore. We are using [Nebula-Operator helm charts](https://github.com/vesoft-inc/nebula-operator/tree/master/charts)
- Do you have any suggestions?

**Reply by wey-gu** [reply]
@porscheme confirmed with @kqzh that if storage number remains the same, in enterprise version of nebulagraph br, backup and restore across different cluster is supported now.

**Reply by wey-gu** [reply]
> Thanks @wey-gu for the reply.
> 
> * There is no way to attach a NFS volume to Nebula cluster for backup & restore. We are using [Nebula-Operator helm charts](https://github.com/vesoft-inc/nebula-operator/tree/master/charts)
> * Do you have any suggestions?

Another thing is BR is not fully supported for K8s/container deployment use cases, the process of backup and restore are about downloading, and uploading **files** to a centralized storage endpoint(S3-compatible objective storage now) instead of moving folders for NFS or other POSIX-like storage backend.

We are working on adding BR support for k8s now.

**Comment by porscheme** [comment]
@wey-gu thanks for the reply.

why not allow attaching additional volume/volumeMount to storaged? This will quickly unblock people like us. We can attach NFS drive and enable BR. The helm chats are too limiting...cannot customize or extend.

**Reply by wey-gu** [reply]
To support POSIX-like mounting storage and leveraging storage layer file replication feature is quite advanced and I personally think it's doable, too, could you raise issues on nebula-br repo on this?

Regarding helm charts, configurable-capability, is it due to the limitation of the helm itself or due to lacking configuration options on the NebulaCluster Options itself?

**Reply by porscheme** [reply]
@wey-gu thanks for the reply.

> Regarding helm charts, configurable-capability, is it due to the limitation of the helm itself or due to lacking configuration options on the NebulaCluster Options itself?

- Its hard to extend, no doc or sample
- For Example, Helm Charts have something called sidecarContainers/sidecarVolumes
- IMHO, this can be used to attached NFS but need example

**Reply by porscheme** [reply]
Sorry, I take back my comment on Sidecar.

-I added following to Helm Charts values file for storaged.
-I could access the NFS from busybox container, but not from storaged.
```
    sidecarContainers: 
      - name: sidecar-container
        image: busybox
        command: ["sh","-c","while true; do touch /mnt/sparkdata/access.log; sleep 30; done"]
        volumeMounts:
          - name: sparkdatadir
            mountPath: /mnt/sparkdata
    sidecarVolumes:
      - name: sparkdatadir
        persistentVolumeClaim:
          claimName: spark-data-nfs-pvc
```
