### DISCUSSION TITLE
How to limit NebulaGraph GraphD memory in Docker-Compose

### DISCUSSION THREAD

**Discussion by wey-gu** [vesoft-inc/nebula#4860] [General]
By default, when deploying NebulaGraph in docker compose for test purposes, the OOM won't be triggered as other bare-metal processes, thus it will exhausted your ram when some crazy query was shot.

this is what we could do:

1. Add the memory limit with `deploy.resources.limits.memory: "160G"` to the compose yaml file to ensure your graphd won't eat memory larger than 160G.

```yaml
  graphd:
    image: vesoft/nebula-graphd:v3.2.0
    deploy:
      resources:
        limits:
          memory: "160G"
    environment:
      USER: root
      TZ:   "${TZ}"
```
2. add `--compatibility` to your up command, otherwise the deploy config will be ignored as it's designed for swarm mode only.

```bash
docker-compose --compatibility up -d
```

Then we could see from stats that `graphd` is no with Mem Limitation:

```bash
❯ docker stats --no-stream
CONTAINER ID   NAME                                CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
27d94034f070   nebula-docker-compose_graphd_1      0.04%     57.17MiB / 160GiB     0.03%     34.1kB / 46.1kB   0B / 0B           170
e6d4e51eb214   nebula-docker-compose_console_1     0.00%     3.73MiB / 188.8GiB    0.00%     2.33kB / 1.74kB   15.4MB / 0B       2
c888d8c27f51   nebula-graph-studio-v323_web_1      0.00%     488.4MiB / 188.8GiB   0.25%     335MB / 56.7MB    6.97GB / 65.5kB   79
c9df7f01fa77   nebula-graph-studio-350_web_1       0.36%     80.32MiB / 188.8GiB   0.04%     391MB / 692MB     4.03GB / 270kB    78
```
