### DISCUSSION TITLE
Fulltext search and listener setup

### DISCUSSION THREAD

**Discussion by ples** [vesoft-inc/nebula#5931] [Q&A]
I'm trying to setup fulltext search on K8s (using nebula k8 operator) and I have an issue with listener step. Here is my listener setup:

```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-listener
  labels:
    app: nebula-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nebula-listener
  template:
    metadata:
      labels:
        app: nebula-listener
    spec:
      containers:
        - name: nebula-listener
          image: docker.io/vesoft/nebula-storaged:v3.8.0
          ports:
            - containerPort: 9789
            - containerPort: 9790
            - containerPort: 19789
            - containerPort: 19790
          command:
            - /usr/local/nebula/bin/nebula-storaged
            - --flagfile=/usr/local/nebula/etc/nebula-storaged.conf
            - --daemonize=false
          args:
            - --meta_server_addrs=nebula-metad-headless:9559
            - --local_ip=127.0.0.1
            - --ws_ip=0.0.0.0
            - --port=9789
            - --ws_http_port=19789
            - --heartbeat_interval_secs=10
            - --listener_path=/data/listener
            # - --log_dir=/logs
            # log to stderr not file
            - --logtostderr=true
            - --redirect_stdout=false
            # log to stderr not file
            - --v=3
            - --minloglevel=0
---
apiVersion: v1
kind: Service
metadata:
  name: nebula-listener-svc
spec:
  clusterIP: 172.20.77.72
  selector:
    app: nebula-listener
  ports:
    - protocol: TCP
      name: listener
      port: 9789
      targetPort: 9789
    - protocol: TCP
      name: listener-1
      port: 9790
      targetPort: 9789
    - protocol: TCP
      name: ws
      port: 19789
      targetPort: 19789
    - protocol: TCP
      name: ws-1
      port: 19790
      targetPort: 19790

```
As you can see I'm using cluster IP 172.20.77.72 and registering listener via `ADD LISTENER ELASTICSEARCH 172.20.77.72:9789`
On the storaged pods I see next logs:

```
I20240820 07:53:22.405108    69 ThriftClientManager-inl.h:47] Getting a client to "172.20.77.72":9790
I20240820 07:53:22.405731    69 Host.cpp:429] [Port: 9780, Space: 28, Part: 2] [Host: 172.20.77.72:9790] Heartbeat: apache::thrift::TApplicationException: Method name heartbeat not found
I20240820 07:53:22.405776    69 CollectNSucceeded-inl.h:59] Set Value [completed=1, total=1, Result list size=1]
```

The question is what can be wrong with my setup? Did somebody try to configure listener instance on K8?
