### ISSUE TITLE
readline6 not available in Ubuntu

### ISSUE THREAD

**Issue by crimeminister** [vesoft-inc/nebula#2317]
**Describe the bug**

It seems as though `readline6` is [not available](https://bugs.launchpad.net/ubuntu/+source/readline6/+bug/1805040) in recent Ubuntu distributions; applications are encouraged to migrate to readline7 or later. As a result, I am unable to execute `nebula` after installing from `.deb` on an Ubuntu system. 

**Your Environments**

* OS:
```
Linux solace 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
* Compiler:
```
g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
```
* CPU:
```
Architecture:                    x86_64
CPU(s):                          8
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz
```

**How To Reproduce**

After installing nebula:

```shell
$ dpkg -i nebula-1.0.1.ubuntu1604.amd64.deb
```
I attempt to run the `nebula` binary:
```shell
$ /usr/local/nebula/bin/nebula
```
I receive the following error message:
```
/usr/local/nebula/bin/nebula: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
```
Checking with `ldd` I find that:
```shell
$ ldd /usr/local/nebula/bin/nebula
	linux-vdso.so.1 (0x00007ffc3eed2000)
	libreadline.so.6 => not found
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f7b7136b000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f7b7133d000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f7b71321000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7b7131b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7b711cc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7b711a7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7b70fb5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7b713c0000)
```

**Expected behavior**

Pre-packaged `nebula` should be link against a newer `readline` and work "out of the box".

**Comment by laura-ding** [comment]
@crimeminister Thanks for your question. You need to download the `nebula-1.0.1.ubuntu1804.amd64.deb`. The readline of `nebula-1.0.1.ubuntu1804.amd64.deb` is `7`.

**Comment by crimeminister** [comment]
@laura-ding Thanks, that did the trick. Rookie mistake on my part! In case it helps someone else, here's the Ansible script I use to install Nebula locally:

```yaml
# Ansible playbook for installing Nebula Graph.
---

# NB: by default, the .deb installs nebula to:
#   /usr/local/nebula
# Start all services by running:
#   $ /usr/local/nebula/scripts/nebula.service start
# Check the status of the running services:
#   $ /usr/local/nebula/scripts/nebula.service status all

- debug:
    msg: "undefined variable: nebula_version"
  when: nebula_version is not defined

- debug:
    msg: "undefined variable: nebula_distro"
  when: nebula_distro is not defined

- debug:
    msg: "undefined variable: nebula_arch"
  when: nebula_arch is not defined

- set_fact:
    # The name of the nebula apt package
    apt_name: nebula-graph
    # The default installation location for nebula.
    install_dir: "/usr/local/nebula"
    # The .deb and the signature file share this URL prefix.
    deb_url: "https://github.com/vesoft-inc/nebula/releases/download/v{{ nebula_version }}/nebula-{{ nebula_version }}.{{ nebula_distro }}.{{ nebula_arch }}.deb"

- set_fact:
    # URL of the signature file.
    signature_url: "{{ deb_url }}.sha256sum.txt"
    # URL of the release binary.
    download_url: "{{ deb_url }}"

- name: check if nebula already installed
  stat:
    path: "{{ install_dir }}"
  register: nebula_dir

- set_fact:
    nebula_installed: true
  when: nebula_dir.stat.exists

  ## Ensure an existing installation of nebula is removed before installing the new version.

- name: stop nebula services
  shell: "{{ install_dir }}/scripts/nebula.service stop all"
  when: nebula_installed
  become: true

- name: uninstall currently installed nebula
  apt:
    name: "{{ apt_name }}"
    state: absent
  when: nebula_installed
  become: true

  ## Download and install nebula.

- tempfile:
    state: directory
    prefix: ansible-
    suffix: -nebula
  register: tmp_dir

- name: download signature file
  get_url:
    url: "{{ signature_url }}"
    dest: "{{ tmp_dir.path }}/shasum256.txt"
    mode: 0600
    timeout: 120

- name: extract shasum
  shell: cat "{{ tmp_dir.path }}/shasum256.txt" | cut -f 1 -d ' '
  register: sha_sum

- set_fact:
    sha256_sum: "sha256:{{ sha_sum.stdout }}"

- debug:
    msg: "extracted hash: {{ sha256_sum }}"

- name: download release binary
  get_url:
    url: "{{ download_url }}"
    dest: "{{ tmp_dir.path }}/nebula-graph.deb"
    mode: 0600
    timeout: 512
    checksum: "{{ sha256_sum }}"

- name: install application with dpkg
  apt:
    deb: "{{ tmp_dir.path }}/nebula-graph.deb"
  become: yes

- file:
    path: "{{ tmp_dir.path }}"
    state: absent
```
Thanks for open sourcing this great tool!
