### ISSUE TITLE
use k8s runner for action, and use labels to separate jobs 

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#3060]
coverage in nightly job is always failed, cause we have some runner with 40GB memory, and jobs would OOM for `ubuntu2004, gcc-9.2`

1. use k8s pod with resource limit as action runner
2. separate jobs via labels.

e.g.

```
  build-ubuntu:
    name: build
    needs: lint
    runs-on: [self-hosted, ubuntu]
    strategy:

  build-centos:
    name: build
    needs: lint
    runs-on: [self-hosted, centos]
    strategy:
```
