### ISSUE TITLE
docker-compose storaged faild

### ISSUE THREAD

**Issue by panla** [vesoft-inc/nebula#4322]
### version

- metda: v3.1.0
- storaged: v3.1.0
- graphd: v3.1.0

### log

```text
I20220614 16:37:25.201115     1 StorageDaemon.cpp:129] localhost = "nebula-storaged0":9779
I20220614 16:37:25.201246     1 StorageDaemon.cpp:144] data path= /data/storage
I20220614 16:37:25.204864     1 MetaClient.cpp:80] Create meta client to "nebula-metad0":9559
I20220614 16:37:25.204892     1 MetaClient.cpp:81] root path: /usr/local/nebula, data path size: 1
W20220614 16:37:25.204919     1 FileBasedClusterIdMan.cpp:43] Open file failed, error No such file or directory
I20220614 16:37:25.215701    48 ThriftClientManager-inl.h:67] resolve "nebula-metad2":9559 as "172.21.0.5":9559
I20220614 16:37:26.219305    48 ThriftClientManager-inl.h:67] resolve "nebula-metad0":9559 as "172.21.0.3":9559
E20220614 16:37:28.227651     1 MetaClient.cpp:98] Heartbeat failed, status:Machine not existed!
I20220614 16:37:28.227782     1 MetaClient.cpp:123] Waiting for the metad to be ready!
W20220614 16:37:38.227864     1 FileBasedClusterIdMan.cpp:43] Open file failed, error No such file or directory
I20220614 16:37:38.228451    54 ThriftClientManager-inl.h:67] resolve "nebula-metad0":9559 as "172.21.0.3":9559
E20220614 16:37:41.239555     1 MetaClient.cpp:98] Heartbeat failed, status:Machine not existed!
I20220614 16:37:41.239581     1 MetaClient.cpp:123] Waiting for the metad to be ready!

```

### yaml

```yaml
version: '3.9'
services:

  storaged0:
    image: vesoft/nebula-storaged:v3.1.0
    container_name: nebula-storaged0
    command:
      - --meta_server_addrs=nebula-metad0:9559,nebula-metad1:9559,nebula-metad2:9559
      - --local_ip=nebula-storaged0
      - --ws_ip=nebula-storaged0
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    # restart: alyways
    networks:
      - nebula-net
    ports:
      - "9701:9779"
      - "9702:19779"
      - "9703:19780"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/storaged0:/data/storage
      - ./logs/storaged0:/logs
    environment:
      USER: root
    # depends_on:
    #   - metad0
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://nebula-storaged0:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    cap_add:
      - SYS_PTRACE

  # storaged1
  # storaged2

networks:
  nebula-net:
    external: true

```

### other containers

- nebula-metad0, nebula-metad1, nebula-metad2: healthy
- nebula-storaged0, nebula-storaged1, nebula-storaged2: unhealthy
