### ISSUE TITLE
Helm install nebula v3.4.0

### ISSUE THREAD

**Issue by SakaZhang** [vesoft-inc/nebula#5641]
Here is my helm values.yaml:
```
nebula:
  version: v3.4.0
  imagePullPolicy: IfNotPresent
  storageClassName: "kadalu.gfs"
  enablePVReclaim: false
  enableBR: false
  enableForceUpdate: false
  schedulerName: default-scheduler # nebula-scheduler
  unsatisfiableAction: ScheduleAnyway
  logRotate: { }
  reference:
    name: statefulsets.apps
    version: v1
  graphd:
    image: harbor.minum.cloud/pub/nebula-graphd
    replicas: 2
    serviceType: NodePort
    env: []
    config: {}
    logStorage: "500Mi"
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    initContainers: []
    sidecarContainers: []
    sidecarVolumes: []

  metad:
    image: harbor.minum.cloud/pub/nebula-metad
    replicas: 1
    env: []
    config: {}
    logStorage: "500Mi"
    dataStorage: "2Gi"
    license: {}
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    initContainers: []
    sidecarContainers: []
    sidecarVolumes: []

  storaged:
    image: harbor.minum.cloud/pub/nebula-storaged
    replicas: 1
    env: []
    config: {}
    resources:
    logStorage: "500Mi"
    dataStorage: "10Gi"
    enableAutoBalance: false
    podLabels: {}
    podAnnotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    readinessProbe: {}
    initContainers: []
    sidecarContainers: []
    sidecarVolumes: []

  exporter:
    image: harbor.minum.cloud/pub/nebula-stats-exporter
    version: v3.3.0
    replicas: 1
    env: [ ]
    podLabels: { }
    podAnnotations: { }
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    livenessProbe: { }


imagePullSecrets:
  - name: harbor
nameOverride: ""
fullnameOverride: ""
```

The nebula-metad pod got `CrashLoopBackOff` and here is the log:
```
+ exec /usr/local/nebula/bin/nebula-metad --flagfile=/usr/local/nebula/etc/nebula-metad.conf --meta_server_addrs=nebula-cluster-metad-0.nebula-cluster-metad-headless.minum.svc.dev.minum:9559 --local_ip=nebula-cluster-metad-0.nebula-cluster-metad-headless.minum.svc.dev.minum --ws_ip=nebula-cluster-metad-0.nebula-cluster-metad-headless.minum.svc.dev.minum --daemonize=false
E0717 11:36:55.423256     1 MetaDaemon.cpp:207] Bad local host addr, status:Bad ip format:nebula-cluster-metad-0.nebula-cluster-metad-headless.minum.svc.dev.minum
```
The service name is correct and i can nslookup this service name in another container.
