### ISSUE TITLE
deploy by docker swarm , alway error, "MetaDaemonInit.cpp:118] Leader has not been elected, sleep 1s"

### ISSUE THREAD

**Issue by hetao29** [vesoft-inc/nebula#5847]
## Cannot run metad when use docker swarm deploy

```yml
version: "3.9"
services:
  metad1:
    image: docker.io/vesoft/nebula-metad:v3.6.0
    environment:
      USER: root
    command:
      - --meta_server_addrs=nebula_graph_meta_metad1:9559
      - --local_ip=0.0.0.0
      - --ws_ip=nebula_graph_metad_metad1
      - --port=9559
      - --ws_http_port=19559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    ports:
      - 9559:9559
      - 19559:19559
      - 19560:19560
    volumes:
      - /data/nebula-graph/data/meta1:/data/meta
      - /data/nebula-graph/logs/meta1:/logs
    restart: on-failure
    cap_add:
      - SYS_PTRACE
```

```bash
docker stack deploy --with-registry-auth -c docker-compose-meta.yml nebula_graph_meta
```

and error in metad-stderr.log

```log
I20240402 06:10:08.398849     1 MetaDaemonInit.cpp:118] Leader has not been elected, sleep 1s
```
