### ISSUE TITLE
Add readiness probe for storage/meta/graph services

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#955]
Now nebula has a http endpoint `/status` to check the service liveness. A readiness probe for checking whether a service is ready for serving is also necessary for many scheduler like kubernetes or docker swarm. By the readiness probe, nebula will avoid some errors of syncing data between storage and meta services at the beginning.

**Comment by ljluestc** [comment]
Kubernetes Readiness Probes
When deploying NebulaGraph services in Kubernetes, you would typically define the readiness probes within your Deployment or StatefulSet configuration:

For Storage Service:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nebula-storage
spec:
  serviceName: nebula-storage
  replicas: 3
  selector:
    matchLabels:
      app: nebula-storage
  template:
    metadata:
      labels:
        app: nebula-storage
    spec:
      containers:
      - name: nebula-storage
        image: vesoft/nebula-storaged:latest
        ports:
        - containerPort: 9779
        readinessProbe:
          httpGet:
            path: /status
            port: 19779  # Assuming the status endpoint is available on this port
          initialDelaySeconds: 10
          periodSeconds: 5
```

For Meta Service:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nebula-meta
spec:
  serviceName: nebula-meta
  replicas: 3
  selector:
    matchLabels:
      app: nebula-meta
  template:
    metadata:
      labels:
        app: nebula-meta
    spec:
      containers:
      - name: nebula-meta
        image: vesoft/nebula-metad:latest
        ports:
        - containerPort: 9559
        readinessProbe:
          httpGet:
            path: /status
            port: 19559  # Assuming the status endpoint for meta service
          initialDelaySeconds: 10
          periodSeconds: 5
```

For Graph Service:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-graph
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nebula-graph
  template:
    metadata:
      labels:
        app: nebula-graph
    spec:
      containers:
      - name: nebula-graph
        image: vesoft/nebula-graphd:latest
        ports:
        - containerPort: 9669
        readinessProbe:
          httpGet:
            path: /status
            port: 19669  # Assuming the status endpoint for graph service
          initialDelaySeconds: 10
          periodSeconds: 5
```

Notes on Configuration:
initialDelaySeconds: Specifies how long to wait before starting to probe after the container starts.
periodSeconds: How often (in seconds) to perform the probe.
httpGet: Uses HTTP GET request to check if the service is ready. The /status endpoint should return successfully (typically 200-399 status codes) when the service is ready.

Docker Swarm Readiness Probes
In Docker Swarm, you can add health checks (which serve a similar purpose to Kubernetes readiness probes) to your services. Here's an example for each service:

```
version: "3.8"

services:
  nebula-storage:
    image: vesoft/nebula-storaged:latest
    ports:
      - "9779:9779"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:19779/status"]
        interval: 5s
        timeout: 2s
        retries: 3
        start_period: 10s

  nebula-meta:
    image: vesoft/nebula-metad:latest
    ports:
      - "9559:9559"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:19559/status"]
        interval: 5s
        timeout: 2s
        retries: 3
        start_period: 10s

  nebula-graph:
    image: vesoft/nebula-graphd:latest
    ports:
      - "9669:9669"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:19669/status"]
        interval: 5s
        timeout: 2s
        retries: 3
        start_period: 10s
```

Notes on Docker Swarm Configuration:
healthcheck is used instead of readinessProbe, but it serves a similar purpose by checking the health of the container.
start_period in Docker is analogous to initialDelaySeconds in Kubernetes, giving the service time to start up before health checks begin.

Make sure to adjust port numbers and endpoints according to the actual configuration of your NebulaGraph services. Remember, these configurations are to ensure that services are ready before they start serving traffic, thus avoiding early data sync errors or other initialization problems.
